# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: dckfo1c47633g2
  pool: 5
  host: ec2-54-225-157-157.compute-1.amazonaws.com
  username: tkligmptxihmkg
  password: 63qLjSufGkWPxSouUXnXZuASVH
port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: d7n5d9pqj2cem2
  pool: 5
  host: ec2-54-225-157-157.compute-1.amazonaws.com
  username: yjdjhuxvtyucjl
  password: xtu39encuHV0lMfn4o9rO_sPdg
port: 5432
