production:
  adapter: postgresql
  encoding: unicode
  database: d13ivlrphsjd6
  pool: 5
  host: ec2-54-221-249-3.compute-1.amazonaws.com
  username: zohantvwriityi
  password: A3deJnDSF5sG_J2-5LNb49yIX6
port: 5432

production_sec:
  adapter: postgresql
  encoding: unicode
  database: dckfo1c47633g2
  pool: 5
  host: ec2-54-225-157-157.compute-1.amazonaws.com
  username: tkligmptxihmkg
  password: 63qLjSufGkWPxSouUXnXZuASVH
port: 5432